# Site settings
title: Coding After Hours
email: henrique.j.graca@gmail.com
description: "ramblings of an enthusiastic Web developer"
#baseurl: ""
url: "http://hjgraca.github.io/"
twitter_username: hjgraca
github_username:  hjgraca
stackoverflow_username:  727141
linkedin_username: hjgraca

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
exclude: ["node_modules"]

gems: [jekyll-paginate]